draw_config:
  key_w: 64.0
  key_h: 64.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: false
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1
  arc_radius: 6.0
  append_colon_to_layer_header: false
  small_pad: 4.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: true
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  svg_extra_style: |
    rect,
    path {
      shape-rendering: geometricPrecision;
    }
    svg.keymap {
      font-weight: 400;
      color: #500724;
      fill: #500724;
      font-size: 16px;
    }
    rect.key {
      fill: #fde9f4;
      stroke: #f9a8d4;
      stroke-width: 1;
    }
    rect.key.held {
      fill: #f9a8d4 !important;
      stroke: #ec4899 !important;
    }
    .keypos-0 rect.key,
    .keypos-7 rect.key {
      fill: #bae6fd;
      stroke: #0ea5e9;
    }
    .keypos-12 rect.key,
    .keypos-19 rect.key {
      fill: #fef08a;
      stroke: #eab308;
    }
    .keypos-5,
    .keypos-6,
    .keypos-17,
    .keypos-18,
    .keypos-29,
    .keypos-30,
    .keypos-38 {
      display: none;
    }
    .none {
      opacity: 0.75;
    }
    .label {
      text-transform: uppercase;
    }
  footer_text: ''
  shrink_wide_legends: 7
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
  glyph_urls:
    tabler: https://unpkg.com/@tabler/icons/icons/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
    phosphor: "https://unpkg.com/@phosphor-icons/core/assets/{}.svg",
  use_local_cache: true
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    '&soft_off': $$phosphor:regular/power$$
    '&caps_word':
      tap: $$phosphor:regular/arrow-fat-line-up$$
      shifted: word
    '&mmv MOVE_LEFT': 
      tap: $$phosphor:regular/mouse$$
      shifted: $$phosphor:regular/caret-double-left$$
    '&mmv MOVE_DOWN':
      tap: $$phosphor:regular/mouse$$
      shifted: $$phosphor:regular/caret-double-down$$
    '&mmv MOVE_UP':
      tap: $$phosphor:regular/mouse$$
      shifted: $$phosphor:regular/caret-double-up$$
    '&mmv MOVE_RIGHT':
      tap: $$phosphor:regular/mouse$$
      shifted: $$phosphor:regular/caret-double-right$$
    '&msc SCRL_LEFT':
      tap: $$phosphor:regular/mouse-scroll$$
      shifted: $$phosphor:regular/caret-double-left$$
    '&msc SCRL_DOWN':
      tap: $$phosphor:regular/mouse-scroll$$
      shifted: $$phosphor:regular/caret-double-down$$
    '&msc SCRL_UP':
      tap: $$phosphor:regular/mouse-scroll$$
      shifted: $$phosphor:regular/caret-double-up$$
    '&msc SCRL_RIGHT':
      tap: $$phosphor:regular/mouse-scroll$$
      shifted: $$phosphor:regular/caret-double-right$$
    '&mkp MCLK': $$phosphor:regular/mouse-middle-click$$
    '&mkp LCLK': $$phosphor:regular/mouse-left-click$$
    '&mkp RCLK': $$phosphor:regular/mouse-right-click$$
    '&out OUT_BLE':
      tap: $$phosphor:regular/keyboard$$
      shifted: $$phosphor:regular/bluetooth$$
    '&out OUT_USB':
      tap: $$phosphor:regular/keyboard$$
      shifted: $$phosphor:regular/usb$$
    '&bt BT_PRV':
      tap: $$phosphor:regular/skip-back$$
      hold: $$phosphor:regular/bluetooth$$
    '&bt BT_NXT':
      tap: $$phosphor:regular/skip-forward$$
      hold: $$phosphor:regular/bluetooth$$
    '&bt BT_CLR':
      tap: $$phosphor:regular/trash-simple$$
      hold: $$phosphor:regular/bluetooth$$
    '&bt BT_CLR_ALL': 
      tap: $$phosphor:regular/trash$$
      hold: $$phosphor:regular/bluetooth$$
    '&bt BT_SEL 0':
      tap: 0
      hold: $$phosphor:regular/bluetooth-connected$$
    '&bt BT_SEL 1':
      tap: 1
      hold: $$phosphor:regular/bluetooth-connected$$
    '&bt BT_SEL 2':
      tap: 2
      hold: $$phosphor:regular/bluetooth-connected$$
    '&bt BT_SEL 3':
      tap: 3
      hold: $$phosphor:regular/bluetooth-connected$$
    '&bt BT_SEL 4':
      tap: 4
      hold: $$phosphor:regular/bluetooth-connected$$
    '&bt BT_DISC 0':
      tap: 0
      hold: $$phosphor:regular/bluetooth-slash$$
    '&bt BT_DISC 1':
      tap: 1
      hold: $$phosphor:regular/bluetooth-slash$$
    '&bt BT_DISC 2':
      tap: 2
      hold: $$phosphor:regular/bluetooth-slash$$
    '&bt BT_DISC 3':
      tap: 3
      hold: $$phosphor:regular/bluetooth-slash$$
    '&bt BT_DISC 4':
      tap: 4
      hold: $$phosphor:regular/bluetooth-slash$$
    '&mo 7':
      hold: bluetooth
    "&none":
      type: none
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: Sft
    right_shift: Sft
    left_alt: Alt
    right_alt: AGr
    left_gui: Gui
    right_gui: Gui
    keycode_combiner: '{mods}+ {key}'
    mod_combiner: '{mod_1}+{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  qmk_remove_keycode_prefix:
  - KC_
  qmk_keycode_map:
    XXXXXXX: ''
    'NO': ''
    MINUS: '-'
    MINS: '-'
    EQUAL: '='
    EQL: '='
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    RBRC: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
  zmk_keycode_map:
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
    LGUI: $$phosphor:regular/command$$
    RGUI: $$phosphor:regular/command$$
    LCTRL: $$phosphor:regular/control$$
    RCTRL: $$phosphor:regular/control$$
    LALT: $$phosphor:regular/option$$
    RALT: 
      tap: $$phosphor:regular/option$$
      hold: $$phosphor:regular/caret-right$$
    LSHFT: $$phosphor:regular/arrow-fat-up$$
    RSHFT: $$phosphor:regular/arrow-fat-up$$
    QUOT: "'"
    PSCRN: $$phosphor:regular/crop$$
    LEFT: $$phosphor:regular/arrow-left$$
    RIGHT: $$phosphor:regular/arrow-right$$
    UP: $$phosphor:regular/arrow-up$$
    DOWN: $$phosphor:regular/arrow-down$$
    HOME: $$phosphor:regular/caret-line-left$$
    PG_DN: $$phosphor:regular/caret-line-down$$
    PG_UP: $$phosphor:regular/caret-line-up$$
    END: $$phosphor:regular/caret-line-right$$
    CAPS: $$phosphor:regular/arrow-fat-line-up$$
    K_PASTE: $$phosphor:regular/clipboard$$
    K_COPY: $$phosphor:regular/copy$$
    K_CUT: $$phosphor:regular/scissors$$
    SPACE: $$material:space_bar$$
    BSPC: $$phosphor:regular/backspace$$
    C_VOL_DN: $$phosphor:regular/speaker-simple-low$$
    C_VOL_UP: $$phosphor:regular/speaker-simple-high$$
    C_PREV: $$phosphor:regular/skip-back$$
    C_NEXT: $$phosphor:regular/skip-forward$$
    C_BRI_DN: $$phosphor:regular/sun-dim$$
    C_BRI_UP: $$phosphor:regular/sun$$
    C_PP: $$phosphor:regular/play-pause$$
    C_STOP: $$phosphor:regular/stop$$
    C_MUTE: $$phosphor:regular/speaker-simple-x$$
    INS: $$phosphor:regular/download-simple$$
    DELETE: $$phosphor:regular/trash$$
    TAB: $$phosphor:regular/arrows-left-right$$
    ENTER: $$phosphor:regular/arrow-bend-down-left$$
    BACKSPACE: $$phosphor:regular/backspace$$
    ESC: $$phosphor:regular/sign-out$$
  zmk_combos: {}
